Repository Clueless-Community/Spectrum-UI, pull requests merged in 2023-05, with the labels that each got.

#159 Enhanced the splash screen
  lib/screens/splash_screen.dart
Labels: good first issue, GSSOC23

#160 Added functionality to copy button
  lib/screens/main_app_widgets/about_page.dart
  pubspec.lock
  pubspec.yaml
Labels: good first issue, GSSOC23

#165 Updated Icon in pricing cards
  lib/ui_components/pricing_cards/All Pricing Cards/pricing_card/pricing_cards1.dart
Labels: good first issue, GSSOC23

#158 contributors data added
  lib/screens/main_app_widgets/about_page.dart
  pubspec.yaml
Labels: gssoc23, level2

#179 Create LICENSE
  LICENSE
Labels: gssoc23, level1

#216 Bugs Fixed / UI Updated
  ios/Podfile.lock
  lib/screens/main_app_widgets/fav_page.dart
  lib/ui_components/cards/All Cards/blog_card/card_1.dart
  lib/ui_components/cards/All Cards/blog_card/card_2.dart
  lib/ui_components/cards/All Cards/blog_card_dark_mode/card_5.dart
  lib/ui_components/cards/All Cards/blog_card_dark_mode/card_6.dart
  lib/ui_components/cards/All Cards/social_card/card_3.dart
  lib/ui_components/cards/All Cards/social_card/card_4.dart
  lib/ui_components/cards/All Cards/social_card_dark_mode/card_7.dart
  lib/ui_components/cards/All Cards/social_card_dark_mode/card_8.dart
  lib/ui_components/segmented_controls/segmented_control_screen.dart
  linux/flutter/generated_plugin_registrant.cc
  linux/flutter/generated_plugins.cmake
  macos/Flutter/GeneratedPluginRegistrant.swift
  pubspec.lock
  windows/flutter/generated_plugin_registrant.cc
  windows/flutter/generated_plugins.cmake
Labels: gssoc23, level1

#211 #210 Adding Stepper Widget UIs
  lib/data/widget_category.dart
  lib/ui_components/steppers/steppers.dart
  lib/ui_components/steppers/steppers_widgets/basic_stepper.dart
  lib/ui_components/steppers/steppers_widgets/stepper_with_custom_color.dart
  lib/ui_components/steppers/steppers_widgets/stepper_with_custom_icon.dart
  lib/ui_components/steppers/steppers_widgets/stepper_with_validation.dart
Labels: gssoc23, level2

#198 readme badges added
  README.md
Labels: gssoc23, level1

#205 Added active favorite button
  lib/ui_components/avatars/all_avatars/avatars.dart
  pubspec.lock
Labels: gssoc23, level1

#208 The Issue related to the Bottom_Navigation_Bar has been resolved.
  lib/data/widget_category.dart
  lib/ui_components/bottom_navbars/allBottomNavigationBars/bottom_navbar1.dart
  lib/ui_components/bottom_navbars/allBottomNavigationBars/bottom_navbar2.dart
  lib/ui_components/bottom_navbars/allBottomNavigationBars/bottom_navbar3.dart
  lib/ui_components/bottom_navbars/allBottomNavigationBars/bottom_navbar4.dart
  lib/ui_components/bottom_navbars/allBottomNavigationBars/bottom_navbar5.dart
  lib/ui_components/bottom_navbars/allBottomNavigationBars/bottom_navbar6.dart
  lib/ui_components/bottom_navbars/bottom_navbars.dart
  pubspec.lock
  pubspec.yaml
Labels: gssoc23, level2
