Repository Clueless-Community/Spectrum-UI, pull requests merged in 2023-03, with the labels that each got.

#121 Update CONTRIBUTION.md
  CONTRIBUTION.md
Labels: documentation, MEDIUM, JWOC

#116 button 7 and added const where needed.
  lib/ui_components/buttons/All Buttons/button7.dart
  lib/ui_components/buttons/buttons.dart
Labels: MEDIUM, JWOC

#125 About Page
  assets/about_page_top.png
  assets/profile_photo.jpg
  lib/screens/main_app_widgets/about_page.dart
  lib/screens/main_app_widgets/main_page.dart
  pubspec.yaml
Labels: MEDIUM, JWOC

#127 feat: creating pricing cards UI component
  lib/data/widget_category.dart
  lib/ui_components/pricing_cards/All Pricing Cards/pricing_cards1.dart
  lib/ui_components/pricing_cards/pricing_cards.dart
Labels: WOC

#131 cards and responsive ui
  assets/card_image/cardo.png
  ios/Flutter/Debug.xcconfig
  ios/Flutter/Release.xcconfig
  ios/Podfile
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner.xcworkspace/contents.xcworkspacedata
  lib/data/widget_category.dart
  lib/ui_components/buttons/buttons.dart
  lib/ui_components/cards/All Cards/card_1.dart
  lib/ui_components/cards/All Cards/card_2.dart
  lib/ui_components/cards/All Cards/card_3.dart
  lib/ui_components/cards/All Cards/card_4.dart
  lib/ui_components/cards/All Cards/card_5.dart
  lib/ui_components/cards/All Cards/card_6.dart
  lib/ui_components/cards/All Cards/card_7.dart
  lib/ui_components/cards/All Cards/card_8.dart
  lib/ui_components/cards/cards.dart
  macos/Flutter/Flutter-Debug.xcconfig
  macos/Flutter/Flutter-Release.xcconfig
  macos/Podfile
  macos/Podfile.lock
  macos/Runner.xcodeproj/project.pbxproj
  macos/Runner.xcworkspace/contents.xcworkspacedata
  pubspec.lock
  pubspec.yaml
Labels: UI, JWOC

#143 Pagination Added
  lib/data/widget_category.dart
  lib/ui_components/paginations/all_paginations/page1.dart
  lib/ui_components/paginations/all_paginations/page2.dart
  lib/ui_components/paginations/all_paginations/page3.dart
  lib/ui_components/paginations/all_paginations/page4.dart
  lib/ui_components/paginations/all_paginations/page5.dart
  lib/ui_components/paginations/paginations.dart
Labels: MEDIUM, JWOC
