Repository Clueless-Community/Spectrum-UI, pull requests merged in 2023-06, with the labels that each got.

#235 Added store to local storage feature to the fav list being saved.
  lib/data/hive_database.dart
  lib/data/widget_category.dart
  lib/main.dart
  lib/provider/favorite_provider.dart
  lib/screens/main_app_widgets/fav_page.dart
  lib/screens/main_app_widgets/home_page.dart
  lib/screens/main_app_widgets/search_page.dart
  lib/ui_components/alerts/alerts.dart
  lib/ui_components/avatars/all_avatars/avatars.dart
  lib/ui_components/buttons/buttons.dart
  lib/ui_components/cards/All Cards/blog_card/card_1.dart
  lib/ui_components/cards/All Cards/blog_card/card_2.dart
  lib/ui_components/cards/All Cards/blog_card_dark_mode/card_5.dart
  lib/ui_components/cards/All Cards/blog_card_dark_mode/card_6.dart
  lib/ui_components/cards/All Cards/social_card/card_3.dart
  lib/ui_components/cards/All Cards/social_card/card_4.dart
  lib/ui_components/cards/All Cards/social_card_dark_mode/card_7.dart
  lib/ui_components/cards/All Cards/social_card_dark_mode/card_8.dart
  lib/ui_components/cards/cards.dart
  lib/ui_components/input_fields/input_fields.dart
  lib/ui_components/messages/messages.dart
  lib/ui_components/paginations/paginations.dart
  lib/ui_components/pricing_cards/pricing_cards.dart
  lib/ui_components/progress_bars/progress_bars.dart
  lib/ui_components/radios/radios.dart
  lib/ui_components/segmented_controls/segmented_control_screen.dart
  lib/ui_components/sliders/sliders.dart
  lib/ui_components/steppers/steppers.dart
  lib/ui_components/steppers/steppers_widgets/stepper_with_custom_color.dart
  lib/ui_components/steppers/steppers_widgets/stepper_with_custom_icon.dart
  lib/ui_components/steppers/steppers_widgets/stepper_with_validation.dart
  pubspec.lock
  pubspec.yaml
Labels: gssoc23, level3

#228 [Feature Implimented] The Issue related to the Bottom_Navigation_Bar has been resolved.
  lib/data/widget_category.dart
  lib/ui_components/bottom_navbars/allBottomNavigationBars/animated_navbar/bottom_navbar4.dart
  lib/ui_components/bottom_navbars/allBottomNavigationBars/basic_navbars/bottom_navbar1.dart
  lib/ui_components/bottom_navbars/allBottomNavigationBars/basic_navbars/bottom_navbar2.dart
  lib/ui_components/bottom_navbars/allBottomNavigationBars/fab_navbars/bottom_navbar3.dart
  lib/ui_components/bottom_navbars/allBottomNavigationBars/fab_navbars/bottom_navbar5.dart
  lib/ui_components/bottom_navbars/allBottomNavigationBars/fab_navbars/bottom_navbar6.dart
  lib/ui_components/bottom_navbars/bottom_navbars.dart
Labels: gssoc23, level2

#241 Add to Favorite feature completed
  lib/data/export.dart
  lib/provider/favorite_provider.dart
  lib/ui_components/alerts/alerts.dart
  lib/ui_components/bottom_navbars/allBottomNavigationBars/animated_navbar/bottom_navbar4.dart
  lib/ui_components/bottom_navbars/bottom_navbars.dart
  lib/ui_components/buttons/buttons.dart
  lib/ui_components/cards/cards.dart
  lib/ui_components/input_fields/input_fields.dart
  lib/ui_components/messages/messages.dart
  lib/ui_components/pricing_cards/pricing_cards.dart
  lib/ui_components/radios/radios.dart
  lib/ui_components/segmented_controls/all_segmented_controls/segmented_controls.dart
  lib/ui_components/segmented_controls/segmented_control_screen.dart
  lib/ui_components/sliders/sliders.dart
  lib/ui_components/steppers/steppers.dart
Labels: gssoc23, level2

#238 [Buttons Done] Animated Buttons
  lib/ui_components/buttons/all_buttons/animated_button/button11.dart
  lib/ui_components/buttons/all_buttons/animated_button/button12.dart
  lib/ui_components/buttons/buttons.dart
  pubspec.lock
Labels: gssoc23, level2

#252 Added dependabot.yml file
  .github/dependabot.yml
Labels: gssoc23, level1
