Repository Clueless-Community/Spectrum-UI, pull requests merged in 2023-02, with the labels that each got.

#95 Updated Readme.md
  Contribution.md
  README.md
  assets/Screenshots/Banner alert.png
  assets/Screenshots/Media player.png
  assets/Screenshots/Mobile header.png
  assets/Screenshots/Progress Bar.png
  assets/Screenshots/alert.jpeg
  assets/Screenshots/appbar.png
  assets/Screenshots/calender.png
  assets/Screenshots/checkbox.png
  assets/Screenshots/notification.jpg
  assets/Screenshots/progress indicator.jpg
  assets/Screenshots/text field.png
Labels: EASY, JWOC

#94 fix: alerts with cross fade
  lib/ui_components/alerts/All Alerts/alert1.dart
  lib/ui_components/alerts/All Alerts/alert2.dart
  lib/ui_components/alerts/All Alerts/alert3.dart
  lib/ui_components/alerts/All Alerts/alert4.dart
Labels: WOC

#97 Add the contribution guidelines. #88
  CONTRIBUTION.md
  README.md
Labels: EASY, JWOC

#102 [DOC] Update Readme file new features
  README.md
Labels: EASY, JWOC

#120 Animated Navigation Bar
  assets/icons/favs.png
  assets/icons/favs_filled.png
  assets/icons/home.png
  assets/icons/home_filled.png
  assets/icons/night.png
  assets/icons/night_filled.png
  assets/icons/profile.png
  assets/icons/profile_filled.png
  assets/icons/video.png
  assets/icons/video_filled.png
  lib/main.dart
  lib/screens/bottom_navigation.dart
  lib/screens/main_app_widgets/fav_page.dart
  lib/screens/main_app_widgets/home.dart
  lib/screens/main_app_widgets/main_page.dart
  lib/screens/main_app_widgets/personal_page.dart
  lib/screens/main_app_widgets/random_page.dart
  lib/screens/main_app_widgets/videos_page.dart
  lib/theme/theme.dart
  lib/ui_components/messages/allmessages/message_5.dart
  pubspec.lock
  pubspec.yaml
Labels: JWOC
